name: curvature-metric
channels:
  - conda-forge
  - defaults
dependencies:
  - igl=2.2.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mpmath=1.2.1
  - multipledispatch=0.6.0
  - numpy=1.23.4
  - pandas=1.5.1
  - python=3.9.13
  - scipy=1.9.1
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - tqdm=4.64.1
  - hdf5=1.14.0

