// This file is part of penner-optimization, a constrained parametrization library.
// 
// Copyright (C) 2026 Ryan Capouellez <rjcapouellez@gmail.com>
// 
// This Source Code Form is subject to the terms of the Mozilla Public License 
// v. 2.0. If a copy of the MPL was not distributed with this file, You can 
// obtain one at http://mozilla.org/MPL/2.0/.

#pragma once
#include "util/common.h"

/**
 * @brief Methods for triangulating self overlapping polygons in the plane.
 * 
 * Also supports optimization over triangle area for both the planar and spatial
 * coordinates of the vertices of the polygon.
 * 
 */

/// @file refinement.hh
///
/// Methods to determine if polygons are self-overlapping and triangulate them

namespace Penner {

/// Given three vertices in the plane, compute the triangle area
///
/// @param[in] vertices: three triangle vertices
/// @return face area
Scalar compute_face_area(const std::array<Eigen::VectorXd, 3>& vertices);

/// Given three vertices in the plane, determine if the triangle they form
/// has negative orientation (or area below some threshold).
///
/// @param[in] vertices: three triangle vertices
/// @param[in] threshold: (optional) minimum allowed area to allow before considering numerically inverted
/// @param[in] use_angles: (optional) use corner angles instead of areas
/// @return true iff the triangle is inverted in the uv plane
bool is_inverted_triangle(const std::array<Eigen::Vector2d, 3>& vertices, double threshold=0., bool use_angles=false);

/// Given a list of vertices in the plane, determine if the polygon they
/// determine is self-overlapping.
///
/// Also generates a table indicating if the subpolygons with vertices
/// (i,...,j) are self overlapping and the corresponding splitting vertices.
///
/// @param[in] uv_vertices: list of vertices in the uv plane
/// @param[in] vertices: list of vertices (for minimum face area computation)
/// @param[out] is_self_overlapping_subpolygon: table of subpolygon self
/// 		overlapping predicate truth values
/// @param[out] splitting_vertices: table of splitting vertices for self
///     overlapping subpolygons
/// @param[out] min_face_areas: table of minimum areas of subpolygon areas
/// @param[in] threshold: (optional) minimum allowed area to allow before considering numerically inverted
/// @param[in] use_angles: (optional) use corner angles instead of areas
/// @return true iff the polygon is self-overlapping
bool is_self_overlapping_polygon(
    const std::vector<Eigen::Vector2d>& uv_vertices,
    const std::vector<Eigen::Vector3d>& vertices,
    std::vector<std::vector<bool>>& is_self_overlapping_subpolygon,
    std::vector<std::vector<int>>& splitting_vertices,
    std::vector<std::vector<Scalar>>& min_face_areas,
    double threshold=0.,
    bool use_angles=false);
bool is_self_overlapping_polygon(
    const std::vector<Eigen::Vector2d>& uv_vertices,
    std::vector<std::vector<bool>>& is_self_overlapping_subpolygon,
    std::vector<std::vector<int>>& splitting_vertices,
    std::vector<std::vector<Scalar>>& min_face_areas,
    double threshold=0.,
    bool use_angles=false);

/// Given a table indicating if the subpolygons of a polygon with vertices
/// (i,...,j) are self overlapping and the corresponding splitting vertices,
/// construct a triangulation of the full polygon.
///
/// The tables can be generated by is_self_overlapping_polygon.
///
/// @param[in] is_self_overlapping_subpolygon: table of subpolygon self
/// 		overlapping predicate truth values
/// @param[in] splitting_vertices: table of splitting vertices for self
///     overlapping subpolygons
/// @param[in] min_face_areas: table of minimum areas of subpolygon areas
/// @param[out] faces: list of triangles that triangulate the polygon
void triangulate_self_overlapping_polygon(
    const std::vector<std::vector<bool>>& is_self_overlapping_subpolygon,
    const std::vector<std::vector<int>>& splitting_vertices,
    const std::vector<std::vector<Scalar>>& min_face_areas,
    std::vector<std::array<int, 3>>& faces);


} // namespace Penner